!#/bin/bash

echo "hello planet"
echo "hello universe"
echo "hello galaxy"
echo "hello solar system"
echo "hello world"
echo "hello moon"
echo "hello stars"
echo "hello sun"
echo "hello comets"
echo "hello asteroids"
echo "hello black holes"
echo "hello nebulae"
echo "hello quasars"
echo "hello supernovae"
echo "hello dark matter"
echo "hello dark energy"
echo "hello cosmic microwave background"
echo "hello multiverse"
echo "hello parallel universe"
echo "hello wormholes"
echo "hello time travel"
echo "hello space-time"
echo "hello gravity"
echo "hello relativity"
echo "hello quantum mechanics"
echo "hello string theory"
echo "hello particle physics"
echo "hello astrophysics"
echo "hello cosmology"
echo "hello astronomy"
echo "hello astrophotography"
echo "hello telescopes"
echo "hello satellites"
echo "hello space probes"
echo "hello space shuttles"
echo "hello space stations"
echo "hello rockets"
echo "hello spacecraft"
echo "hello astronauts"
echo "hello cosmonauts"
echo "hello space exploration"
echo "hello space missions"
echo "hello space agencies"
echo "hello NASA"
echo "hello ESA"
echo "hello ISRO"
echo "hello CNSA"
echo "hello JAXA"
echo "hello Roscosmos"
echo "hello SpaceX"
echo "hello Blue Origin"
echo "hello Virgin Galactic"
echo "hello Boeing"
echo "hello Lockheed Martin"
echo "hello Northrop Grumman"
echo "hello Raytheon"
echo "hello Boeing"
echo "hello Airbus"
echo "hello Lockheed Martin"
echo "hello Northrop Grumman"
echo "hello Raytheon"
echo "hello General Dynamics"
echo "hello L3 Harris"
echo "hello BAE Systems"
echo "hello Thales"
echo "hello Leonardo"
echo "hello Saab"
echo "hello Rolls Royce"
echo "hello Thales Alenia Space"
echo "hello Airbus Defence and Space"
echo "hello Boeing Defence, Space and Security"
echo "hello Northrop Grumman Innovation Systems"
echo "hello Rocket Lab"
echo "hello Astra"
echo "hello Relativity Space"
echo "hello Planet Labs"
echo "hello Maxar Technologies"
echo "hello Spire Global"
echo "hello OneWeb"
echo "hello Starlink"
echo "hello Amazon Kuiper"
echo "hello SES"
echo "hello Intelsat"
echo "hello Eutelsat"
echo "hello Inmarsat"
echo "hello Iridium"
echo "hello Globalstar"
echo "hello Orbcomm"
echo "hello Telesat"                                                    